name: PR checks

on:
  pull_request:

jobs:
  fmt-js:
    name: Check JS and Markdown formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno fmt --check --ext=ts init
      - run: deno fmt --check

  fmt-tf:
    name: Check Terraform formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive -diff .
